apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: bmi-cal
  labels:
    run: bmi-cal
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bmi-cal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: bmi-cal
    spec:
      containers:
      - image: jinggegeha/mycalculator
        name: bmi-cal
        ports:
        - containerPort: 7777
        resources: {}
        env:
          - name: JAVA_OPTS
            value: -Dservice.registry.address=http://bmi-service-center:30100
status: {}


