apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: bmi-service-center
  name: bmi-service-center
spec:
  ports:
  - port: 30100
    protocol: TCP
    targetPort: 30100
    nodePort: 30002
  selector:
    run: bmi-service-center
  type: NodePort
status:
  loadBalancer: {}

