apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: bmi-web
  labels:
    run: bmi-web
spec:
  ports:
  - port: 8889
    protocol: TCP
    targetPort: 8889
    nodePort: 30001
  selector:
    run: bmi-web
  type: NodePort
status:
  loadBalancer: {}

