apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: bmi-cal
  labels:
    run: bmi-cal
spec:
  ports:
  - port: 7777
    protocol: TCP
    targetPort: 7777
    nodePort: 30003
  selector:
    run: bmi-cal
  type: NodePort
status:
  loadBalancer: {}

